import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
const files = ['index.tsx', 'package.json', 'README.md'];
export default function ProjectsScreen() {
  const colors = useColors(); const router = useRouter();
  return <ScrollView style={[styles.screen, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><View style={styles.head}><View><Text style={[styles.kicker, { color: colors.primary }]}>WORKSPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Your projects</Text></View><Pressable onPress={() => router.push('/editor')} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={20} color={colors.primaryForeground} /></Pressable></View><Pressable onPress={() => router.push('/editor')} style={[styles.new, { borderColor: colors.primary, backgroundColor: colors.accent }]}><Feather name="zap" size={20} color={colors.primary} /><View><Text style={[styles.newTitle, { color: colors.foreground }]}>Start a new project</Text><Text style={{ color: colors.secondaryForeground, fontSize: 12 }}>Describe your idea and let’s shape it</Text></View></Pressable><Text style={[styles.label, { color: colors.mutedForeground }]}>ALL PROJECTS</Text>{['Habit Garden', 'Studio Dashboard', 'Pocket Journal'].map((name, i) => <Pressable key={name} onPress={() => router.push('/editor')} style={[styles.row, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.folder, { backgroundColor: i === 0 ? '#7DE2A822' : '#9BA7FF22' }]}><Feather name="folder" size={18} color={i === 0 ? '#7DE2A8' : '#9BA7FF'} /></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{name}</Text><Text style={{ color: colors.mutedForeground, fontSize: 12, marginTop: 3 }}>3 files · {i + 1} day ago</Text></View><Feather name="more-horizontal" size={19} color={colors.mutedForeground} /></Pressable>)}<View style={[styles.fileCard, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.label, { color: colors.mutedForeground }]}>STARTER FILES</Text>{files.map(file => <View key={file} style={styles.file}><Feather name={file.endsWith('json') ? 'code' : 'file'} size={16} color={colors.primary} /><Text style={{ color: colors.secondaryForeground }}>{file}</Text></View>)}</View></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, paddingTop: 24, paddingBottom: 120 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, kicker: { fontSize: 11, letterSpacing: 2, fontWeight: '700' }, title: { fontSize: 27, fontWeight: '700', marginTop: 5 }, add: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, new: { flexDirection: 'row', gap: 13, padding: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center', marginBottom: 28 }, newTitle: { fontWeight: '700', marginBottom: 4 }, label: { fontSize: 11, letterSpacing: 1.5, fontWeight: '700', marginBottom: 12 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 16, borderWidth: 1, marginBottom: 10 }, folder: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 15, fontWeight: '600' }, fileCard: { borderRadius: 16, borderWidth: 1, padding: 16, marginTop: 18 }, file: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 9 } });