import AsyncStorage from '@react-native-async-storage/async-storage';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { importPublicGithubRepo } from '@/lib/githubImport';
import { PROJECTS_KEY, ProjectMeta, saveProject, setPreviewUrl } from '@/lib/saveProject';

export default function ProjectsScreen() {
  const colors = useColors(); const router = useRouter(); const [projects, setProjects] = useState<ProjectMeta[]>([]); const [repoUrl, setRepoUrl] = useState(''); const [importing, setImporting] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { AsyncStorage.getItem(PROJECTS_KEY).then(value => value && setProjects(JSON.parse(value))); }, []);
  const importRepo = async () => {
    if (!repoUrl.trim() || importing) return; setImporting(true); setMessage('');
    try { const project = await importPublicGithubRepo(repoUrl, setMessage); const saved = await saveProject(project); await setPreviewUrl(saved.name, project.previewUrl); setProjects(current => [saved, ...current.filter(item => item.name !== saved.name)]); setRepoUrl(''); setMessage('Imported successfully.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'GitHub import failed.'); }
    finally { setImporting(false); }
  };
  return <ScrollView style={[styles.screen, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}>
    <View style={styles.head}><View><Text style={[styles.kicker, { color: colors.primary }]}>WORKSPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Your projects</Text></View><Pressable onPress={() => router.push('/editor')} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={20} color={colors.primaryForeground} /></Pressable></View>
    <View style={[styles.importCard, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.importTitle, { color: colors.foreground }]}>Import from GitHub</Text><Text style={[styles.help, { color: colors.mutedForeground }]}>Paste a public repository URL. Source files are saved locally on this device.</Text><View style={styles.importRow}><TextInput value={repoUrl} onChangeText={setRepoUrl} autoCapitalize="none" autoCorrect={false} placeholder="https://github.com/owner/repo" placeholderTextColor={colors.mutedForeground} style={[styles.repoInput, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={importRepo} style={[styles.importButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: '700' }}>{importing ? '…' : 'Import'}</Text></Pressable></View>{!!message && <Text style={[styles.status, { color: importing ? colors.mutedForeground : colors.primary }]}>{message}</Text>}</View>
    <Pressable onPress={() => router.push('/editor')} style={[styles.new, { borderColor: colors.primary, backgroundColor: colors.accent }]}><Feather name="zap" size={20} color={colors.primary} /><View><Text style={[styles.newTitle, { color: colors.foreground }]}>Start a new project</Text><Text style={{ color: colors.secondaryForeground, fontSize: 12 }}>Describe your idea and let’s shape it</Text></View></Pressable>
    <Text style={[styles.label, { color: colors.mutedForeground }]}>ALL PROJECTS</Text>
    {projects.map((project, i) => <Pressable key={project.name} onPress={() => router.push({ pathname: '/editor', params: { project: project.name } })} style={[styles.row, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.folder, { backgroundColor: i % 2 ? '#9BA7FF22' : '#7DE2A822' }]}><Feather name="folder" size={18} color={i % 2 ? '#9BA7FF' : '#7DE2A8'} /></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{project.name}</Text><Text style={{ color: colors.mutedForeground, fontSize: 12, marginTop: 3 }}>{project.fileCount} files · {new Date(project.created).toLocaleDateString()}</Text></View><Pressable onPress={() => router.push({ pathname: '/preview', params: { project: project.name } })}><Feather name="monitor" size={18} color={colors.primary} /></Pressable></Pressable>)}
    {!projects.length && <Text style={{ color: colors.mutedForeground }}>No local projects yet. Generate one or import a GitHub repository.</Text>}
  </ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, paddingTop: 24, paddingBottom: 120 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, kicker: { fontSize: 11, letterSpacing: 2, fontWeight: '700' }, title: { fontSize: 27, fontWeight: '700', marginTop: 5 }, add: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, importCard: { borderRadius: 16, borderWidth: 1, padding: 15, marginBottom: 14 }, importTitle: { fontWeight: '700', fontSize: 16 }, help: { fontSize: 12, lineHeight: 18, marginTop: 5 }, importRow: { flexDirection: 'row', gap: 8, marginTop: 12 }, repoInput: { flex: 1, borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, fontSize: 12 }, importButton: { borderRadius: 10, paddingHorizontal: 14, justifyContent: 'center' }, status: { fontSize: 12, marginTop: 9 }, new: { flexDirection: 'row', gap: 13, padding: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center', marginBottom: 28 }, newTitle: { fontWeight: '700', marginBottom: 4 }, label: { fontSize: 11, letterSpacing: 1.5, fontWeight: '700', marginBottom: 12 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 16, borderWidth: 1, marginBottom: 10 }, folder: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 15, fontWeight: '600' } });